### ISSUE TITLE
Just a couple of questions..

### ISSUE THREAD

**Issue by gldtn** [sebastianst/yabai3#1]
I've used i3 before but it been a while since I touched Linux, my last time I ended up using xmonad. So can you explain to me the difference here as to what this is trying to accomplish, I'm how is it different from resizing with the built in function of Yabai beside going in to resize mode?

Also, are you able to pull up Alacritty with your config by hitting `alt - return` while Alacritty is closed? As far as I know you can only do that if you're in Linux sending a message straight to the socket (ipc_socket (unix only)).

Sorry for the beginner questions, this is the second script I tried using and I'm struggling to figure out the advantages of it.

Oh, and for some reason even after adding to my path

`export PATH="$HOME/.config/alacritty":$PATH`

I could not get yabai3 to function, I could call it in my terminal, it would resize, but it returned this:

```
yabai3 resize grow height 64
cannot locate a bsp node fence.
```

with the bindings it would go into resize mode, but it wouldn't resize. The only time I got it to resize was by adding the absolute path to my skhdrc

Thanks!

**Comment by sebastianst** [comment]
> So can you explain to me the difference here as to what this is trying to accomplish, I'm how is it different from resizing with the built in function of Yabai beside going in to resize mode?

yabai resizing is more low level compared to i3's resize commands. `yabai3 resize` tries to imitate i3's resizing behavior, which just works. You can see this by looking at the script, it just uses `yabai -m window --resize` with default directions, and it works no matter if a right/left/bottom/top most window is selected, because it tries the opposite direction if the first resize fails.

> Also, are you able to pull up Alacritty with your config by hitting alt - return while Alacritty is closed? As far as I know you can only do that if you're in Linux sending a message straight to the socket (ipc_socket (unix only)).

Yes, that works for me, because I have bound this to
```sh
alacritty msg create-window; open -a Alacritty
```
as explained in the README. This always calls `open -a Alacritty`, which on MacOS starts the application, if it is not already started, and just focuses it otherwise. So if Alacritty isn't running yet, `alacritty msg create-window` will fail, which doesn't matter because `open -a Alacritty` will then just start the app.

> `export PATH="$HOME/.config/alacritty":$PATH`

You shouldn't put configuration directories into your `$PATH`. Better, clone yabai3 somewhere, create a directory for custom binaries and scripts, like `~/bin`, add this one to your path (e.g. `PATH="${HOME}/bin:${PATH}"`), then create a link to the `yabai3` script inside this dir (`cd ~/bin; ln -s ~/path/to/yabai3/yabai3`) and you should be able to invoke `yabai3` from any terminal or script.

> cannot locate a bsp node fence.

This is printed once if you resize a bottom window, which is fine. It should still resize. The way `yabai3` works is that it tries to resize the window as if it is a top window, and if that fails (with this error message), it tries to resize the window as a bottom window. If that also fails, this error message will be printed twice and nothing is resized. This happens if you try to resize the height of a window that already has full height.

In general, you can try out the individual yabai3 commands from a terminal window, before binding keys to it.

**Comment by gldtn** [comment]
Thanks for taking your time and helping me out. For some reason I copied line 63 out of your skhdrc file which only have `alt - return : alacritty-new`.

Everything is working now. Thank you!
